[package]

name = "time"
version = "0.1.37"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/rust-lang/time"
repository = "https://github.com/rust-lang/time"
documentation = "https://doc.rust-lang.org/time"
keywords = ["no_std"]
description = """
Utilities for working with time-related functions in Rust.
"""

[features]
default = ["std"]
std = ["libc"]

[dependencies]
rustc-serialize = { version = "0.3", optional = true }

[dependencies.libc]
version = "0.2.1"
default-features = false
optional = true
features = []

[target.'cfg(target_os = "redox")'.dependencies]
redox_syscall = "0.1"

[target.'cfg(windows)'.dependencies]
winapi = "0.2.0"
kernel32-sys = "0.2.0"

[dev-dependencies]
log = "0.3"

[target.'cfg(windows)'.dev-dependencies]
advapi32-sys = "0.1.2"
