[package]
name = "time"
version = "0.3.0-dev"
authors = ["Jacob Pratt <open-source@jhpratt.dev>", "Time contributors"]
edition = "2018"
repository = "https://github.com/time-rs/time"
keywords = ["date", "time", "calendar", "duration", "parser", "formatter", "no_std", "macro"]
categories = ["date-and-time", "no-std", "parser-implementations"]
readme = "README.md"
license = "MIT OR Apache-2.0"
description = "Date and time library. Fully interoperable with the standard library. Mostly compatible with #![no_std]."
include = ["src/**/*", "LICENSE-*", "README.md", "CHANGELOG.md"]

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
rustc-args = ["--cfg",  "__time_03_docs"]
rustdoc-args = ["--cfg", "__time_03_docs"]

[features]
default = ["std", "const_fn"]
macros = ["time-macros"]
local-offset = ["std", "winapi"]
quickcheck = ["quickcheck-dep", "alloc"]
std = ["alloc"]
alloc = []
large-dates = ["time-macros/large-dates"]

[dependencies]
const_fn = { version = "0.4.5", optional = true }
itoa = { version = "0.4.7", default-features = false } # TODO make optional when formatting is made optional
quickcheck-dep = { package = "quickcheck", version = "1.0.3", optional = true }
rand = { version = "0.8.2", optional = true, default-features = false }
serde = { version = "1.0.119", optional = true, default-features = false, features = ["derive"] }
time-macros = { version = "=0.2.0-dev", path = "time-macros", optional = true }

[workspace]
members = ["time-benchmarks", "time-macros", "time-macros-impl"]

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["minwinbase", "minwindef", "timezoneapi"], optional = true }

[target.'cfg(unsound_local_offset)'.dependencies]
libc = "0.2.82"

[dev-dependencies]
rand = { version = "0.8.2", default-features = false }
serde_json = "1.0.61"
time-macros = { path = "time-macros" }
